<a href="https://colab.research.google.com/github/himanshud2611/PyTorch/blob/main/PyTorch_Fundamentals_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install torch

  Using cached nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (23.7 MB)
  Using cached nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (823 kB)
  Using cached nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (14.1 MB)
  Using cached nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl (731.7 MB)
  Using cached nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl (410.6 MB)
  Using cached nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl (121.6 MB)
  Using cached nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl (56.5 MB)
  Using cached nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl (124.2 MB)
  Using cached nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl (196.0 MB)
  Using cached nvidia_nccl_cu12-2.20.5-py3-none-manylinux2014_x86_64.whl (176.2 MB)
  Using cached nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (99 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.3/21

In [3]:
import torch

1. Documentation reading - A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness). See the documentation on torch.Tensor and for torch.cuda.

2. Create a random tensor with shape (7, 7)

In [6]:
rand_tensor = torch.rand(7,7)
rand_tensor, rand_tensor.shape


(tensor([[0.7665, 0.3086, 0.3958, 0.9782, 0.1636, 0.1626, 0.2852],
         [0.0526, 0.2599, 0.8455, 0.1192, 0.5635, 0.6609, 0.4012],
         [0.8079, 0.5145, 0.7392, 0.5205, 0.5850, 0.8712, 0.4321],
         [0.3451, 0.5837, 0.0345, 0.7890, 0.9785, 0.6294, 0.2253],
         [0.5198, 0.9635, 0.5378, 0.9379, 0.6616, 0.2355, 0.1572],
         [0.5346, 0.1740, 0.7637, 0.9038, 0.9633, 0.3334, 0.7276],
         [0.3939, 0.5560, 0.1323, 0.6906, 0.9804, 0.1905, 0.6606]]),
 torch.Size([7, 7]))

3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

In [8]:
rand_tensor_2 = torch.rand(1,7)
rand_tensor_2, torch.matmul(rand_tensor, rand_tensor_2.T)

(tensor([[0.4583, 0.2831, 0.9346, 0.3968, 0.5398, 0.2264, 0.3448]]),
 tensor([[1.4201],
         [1.5274],
         [2.0752],
         [1.4170],
         [1.8504],
         [2.2128],
         [1.5357]]))

4. Set the random seed to 0 and do exercises 2 & 3 over again.

In [10]:
import random
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)
rand_tensor_p = torch.rand(7,7)
print(rand_tensor_p), print(rand_tensor_p.shape)

rand_tensor_q = torch.rand(1,7)
print(rand_tensor_q), print(rand_tensor_q.shape)

torch.matmul(rand_tensor_p, rand_tensor_q.T)

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])
torch.Size([7, 7])
tensor([[0.4820, 0.8198, 0.9971, 0.6984, 0.5675, 0.8352, 0.2056]])
torch.Size([1, 7])


tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one). If there is, set the GPU random seed to 1234

In [11]:
gpu_random_seed = 1234
torch.cuda.manual_seed(gpu_random_seed)

6. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed)

In [4]:
torch.manual_seed(1234)
#check for gpu access
torch.cuda.is_available()

True

In [7]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

rand_tensor_A = torch.rand(2,3).to(device)
rand_tensor_B = torch.rand(2,3).to(device)
rand_tensor_A, rand_tensor_B

(tensor([[0.7749, 0.8208, 0.2793],
         [0.6817, 0.2837, 0.6567]], device='cuda:0'),
 tensor([[0.2388, 0.7313, 0.6012],
         [0.3043, 0.2548, 0.6294]], device='cuda:0'))

7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

In [9]:
rand_tensor_c = torch.matmul(rand_tensor_A, rand_tensor_B.T)
rand_tensor_c, rand_tensor_c.shape

(tensor([[0.9531, 0.6207],
         [0.7651, 0.6931]], device='cuda:0'),
 torch.Size([2, 2]))

8. Find the maximum and minimum values of the output of 7.

In [10]:
torch.max(rand_tensor_c), torch.min(rand_tensor_c)

(tensor(0.9531, device='cuda:0'), tensor(0.6207, device='cuda:0'))

9. Find the maximum and minimum index values of the output of 7.

In [11]:
rand_tensor_c.argmax(), rand_tensor_c.argmin()

(tensor(0, device='cuda:0'), tensor(1, device='cuda:0'))

Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [13]:
torch.manual_seed = 7
rand_tensor_v = torch.rand(size=(1,1,1,10))
print(rand_tensor_v), print(rand_tensor_v.shape)

rand_tensor_z = rand_tensor_v.squeeze()
print(rand_tensor_z), print(rand_tensor_z.shape)

tensor([[[[0.5247, 0.6688, 0.8436, 0.4265, 0.9561, 0.0770, 0.4108, 0.0014,
           0.5414, 0.6419]]]])
torch.Size([1, 1, 1, 10])
tensor([0.5247, 0.6688, 0.8436, 0.4265, 0.9561, 0.0770, 0.4108, 0.0014, 0.5414,
        0.6419])
torch.Size([10])


(None, None)